application: fankaicn
version: 1
runtime: python
api_version: 1

handlers:
- url: /data
  static_dir: data

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: required

- url: /store
  script: store.py

- url: /notes
  script: notes.py

- url: /memo.*
  script: /memo.py

- url: /word.*
  script: /word.py

- url: /test
  script: /test.py

- url: /pic
  static_dir: pic

- url: /.*
  script: hello.py


    

