# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
xterm-color)
	PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    ;;
*)
    PS1='\w\$ '
    ;;
esac

# Comment in the above and uncomment this below for a color prompt
#PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
#PS1='\[\033[01;34m\]\w\[\033[00m\]\$ '

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi


# more alias
alias lman='man -M local/man'
alias labftp='lftp ftp://162.105.146.3 -u netlab,netcs'
alias setlabproxy='export http_proxy="http://fankai:123123@162.105.146.2:3128"'
alias unsetproxy='export http_proxy=""'
alias starttomcat='sudo /usr/share/tomcat5.5/bin/startup.sh'
alias stoptomcat='sudo /usr/share/tomcat5.5/bin/startup.sh'
alias mountd='sudo mount -t cofs -o uid=kevin,gid=kevin cofs0 /mnt/d'
alias mounte='sudo mount -t cofs -o uid=fankai,gid=fankai cofs1 /mnt/f'
alias mountf='sudo mount -t cofs -o uid=fankai,gid=fankai cofs1 /mnt/f'

alias hdfs='bin/hadoop fs'
alias hjar='bin/hadoop jar'
alias hjob='bin/hadoop job'

export JAVA_HOME=/usr/lib/jvm/java-6-sun
#export CLASSPATH=/usr/lib/jvm/java-1.5.0-sun/lib
#export CATALINA_HOME=/usr/share/tomcat5.5
export PATH=~/fklab/script:$PATH

